In [23]:
#import numpy as np

In [6]:
 X = [[3,104],
        [2,100],
        [1,81],
        [101,10],
        [99,5],
        [98,2]]
    
Y = [0,0,0,1,1,1]

In [9]:
X = np.array(X)

In [29]:
X.shape

(6, 2)

In [32]:
Y = np.array(Y)
Y

array([0, 0, 0, 1, 1, 1])

In [11]:
Y.shape

(6,)

In [12]:
vera = np.array([[18,90]])
vera.shape #vera是测试样本

(1, 2)

In [13]:
diff = X - vera
diff

array([[-15,  14],
       [-16,  10],
       [-17,  -9],
       [ 83, -80],
       [ 81, -85],
       [ 80, -88]])

In [14]:
s = diff ** 2
s

array([[ 225,  196],
       [ 256,  100],
       [ 289,   81],
       [6889, 6400],
       [6561, 7225],
       [6400, 7744]], dtype=int32)

In [15]:
sum_ = np.sum(s,axis=1)
sum_

array([  421,   356,   370, 13289, 13786, 14144], dtype=int32)

In [19]:
d = sum_ ** 0.5
d

array([ 20.51828453,  18.86796226,  19.23538406, 115.27792503,
       117.41379817, 118.92854998])

In [21]:
K_ = np.argsort(d)[:3]
K_

array([1, 2, 0], dtype=int64)

In [33]:
Y[K_]

array([0, 0, 0])

In [34]:
predict_y_prev =Y[K_]
predict_y_prev

array([0, 0, 0])

In [35]:
np.sum(predict_y_prev) / 3

0.0

In [24]:
import numpy as np

In [25]:
path = "data_set/datingTestSet.txt"

In [26]:
X = []
y = []
with open(path,'r') as f:
    readlines_ = f.readlines()
    for line in readlines_:
        line_split = line.strip('\n').split('\t')
        X.append([np.float32(line_split[0]),np.float32(line_split[1]),np.float32(line_split[2])])
        y.append(line_split[-1])

In [27]:
X = np.array(X)
y = np.array(y)

In [5]:
X =(X - np.min(X,axis=0)) / (np.max(X,axis=0)-np.min(X,axis=0))
X

array([[0.44832537, 0.39805138, 0.5623336 ],
       [0.1587326 , 0.34195465, 0.9872441 ],
       [0.28542942, 0.06892523, 0.4744963 ],
       ...,
       [0.29115948, 0.5091029 , 0.51079494],
       [0.527111  , 0.4366545 , 0.42900482],
       [0.47940794, 0.37680906, 0.7857181 ]], dtype=float32)

In [6]:
random_X_indec = np.random.permutation(1000)

In [7]:
test_X = X[random_X_indec][:200]

In [8]:
test_y = y[random_X_indec][:200]

In [9]:
train_X = X[random_X_indec][200:]

In [10]:
train_y = y[random_X_indec][200:]

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

In [13]:
X_train.shape

(800, 3)

In [14]:
D = np.sum((X_train - X_test[0])**2,axis=1)**0.5
D

array([0.5009853 , 0.67279243, 0.28272453, 0.46856233, 0.58655715,
       0.39310014, 0.69152045, 0.75956815, 0.4271073 , 0.5588441 ,
       0.5699323 , 0.42629477, 0.6930947 , 0.23593444, 0.4603325 ,
       0.6537342 , 0.5233861 , 0.52461344, 0.6141777 , 0.4380009 ,
       0.5629949 , 0.8370085 , 0.4225926 , 0.5882023 , 0.6506874 ,
       0.56228626, 0.7337634 , 0.5968487 , 0.6913893 , 0.4986038 ,
       0.71039236, 0.7047584 , 0.44466203, 0.6166786 , 0.6576316 ,
       0.51050556, 0.5188421 , 0.8039183 , 0.31432244, 0.49291965,
       0.5309116 , 0.03799123, 0.62584287, 0.77650505, 0.5045126 ,
       0.8754828 , 0.6159795 , 0.6895083 , 0.41721296, 0.4482113 ,
       0.31855208, 0.7402264 , 0.5075168 , 0.7060249 , 0.6901071 ,
       0.3314686 , 0.45498756, 0.3259202 , 0.20322882, 0.24819474,
       0.26658872, 0.6565523 , 0.8015435 , 0.41833514, 0.424524  ,
       0.738076  , 0.70853305, 0.6750381 , 0.4506804 , 0.90368474,
       0.4737618 , 0.4223    , 0.55024344, 0.6616583 , 0.31035

In [15]:
sort_D = np.argsort(D)[:5]
sort_D

array([ 41, 589, 507, 336, 133], dtype=int64)

In [16]:
train_y[sort_D]

array(['smallDoses', 'smallDoses', 'largeDoses', 'didntLike', 'didntLike'],
      dtype='<U10')

In [17]:
aaa = train_y[sort_D]
aaa

array(['smallDoses', 'smallDoses', 'largeDoses', 'didntLike', 'didntLike'],
      dtype='<U10')

In [20]:
bbb={}
for i in aaa:
    if i not in bbb.keys():
        bbb[i] = 1
    else:
        bbb[i] += 1
bbb        

{'didntLike': 2, 'largeDoses': 1, 'smallDoses': 2}

In [21]:
ccc=0
predict_y =[]
for key,value in bbb.items():
    if value > ccc:
        ccc = value
        predict_y.append(key)
print(predict_y[-1])

smallDoses


In [29]:
def KNN(X,y,test_X,test_y,K):
    
    PREDICT_y = []
    for i in range(test_X.shape[0]):
        D = np.sum((X - test_X[i])**2,axis=1)**0.5
        sort_D = np.argsort(D)[:K]
        aaa = y[sort_D]
        
        bbb = {}
        for i in aaa:
            if i not in bbb.keys():
                bbb[i] = 1
            else:
                bbb[i] += 1
                
        ccc = 0
        predict_y = []
        for key,value in bbb.items():
            if value > ccc:
                ccc = value
                predict_y.append(key)
                
        PREDICT_y.append(predict_y[-1])
        
    PREDICT_Y = np.array(PREDICT_y)
    
    #####accuracy#####
    accuracy = np.sum(PREDICT_Y == test_y) / test_X.shape[0]
    print(accuracy)

In [34]:
KNN(train_X,train_y,test_X,test_y,10)

0.96


In [29]:
import numpy as np
import os
path_test = "data_set/handwriting/testDigits"
path_train = "data_set/handwriting/trainingDigits"

In [38]:
a = os.listdir(path_test)
b = os.listdir(path_train)
Y = []
X = []
B = []
Z = []
for i in a:
    cache_x = []
    Y.append(i.split('_')[0])
    PATH_test = path_test + '/' + i
    with open(PATH_test,'r')as f:
        lines = f.readlines()
        for j in lines:#遍历每一行
            strip_j = j.strip('\n')
            for k_1 in strip_j:#遍历每一列
                cache_x.append(k)
        X.append(cache_x)
for i in b:
    cache_y = []
    Z.append(i.split('_')[0])
    PATH_train = path_train + '/' + i
    with open(PATH_train,'r')as f:
        lines = f.readlines()
        for j in lines:
            strip_j = j.strip('\n')
            for k in strip_j:
                cache_y.append(k)
        B.append(cache_y)
X = np.array(X)
B = np.array(B)
print(X.shape)
print(B.shape)

(946, 1024)
(1934, 1024)


In [39]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2,random_state=42)
Y_test = np.array(Y_test)
Y_train = np.array(Y_train)
X_train = np.array(X_train)
X_test = np.array(X_test)
B_train, B_test, Z_train, Z_test = train_test_split(B,Z,test_size = 0.8,random_state=42)
Z_test = np.array(Z_test)
Z_train = np.array(Z_train)
B_train = np.array(B_train)
B_test = np.array(B_test)

In [59]:
def KNN(X,Y,test_X,test_Y,K):
    
    PREDICT_y = []
    for i in range(test_X.shape[0]):
       # D =  np.power(np.sum(np.power(X_train - X_test[i],2),axis=1),0.5)
        D = np.sum((X - test_X[i])**2,axis=1)**0.5
        sort_D = np.argsort(D)[:K]
        aaa = Y[sort_D]
        
        bbb = {}
        for i in aaa:
            if i not in bbb.keys():
                bbb[i] = 1
            else:
                bbb[i] += 1
                
        ccc = 0
        predict_y = []
        for key,value in bbb.items():
            if value > ccc:
                ccc = value
                predict_y.append(key)
                
        PREDICT_y.append(predict_y[-1])
        
    PREDICT_Y = np.array(PREDICT_y)
    
    #####accuracy#####
    accuracy = np.sum(PREDICT_Y == test_Y) / test_X.shape[0]
    print(accuracy)

In [63]:
KNN(X_train,Y_train,test_X,test_Y,10)

NameError: name 'test_X' is not defined